name: Build Leaf For Angular
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: 'https://nexus.io-labs.fr/repository/npm-public/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@input-output-labs'
      - run: npm install
      - run: npm run build:lib
      - name: publish package
        if: ${{ success() }}
        run: |
          cp .npmrc dist/ngleaf/.npmrc
          cd dist/ngleaf
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
